### ISSUE TITLE
Personal tracking of Automatic Reconnect & Offline Buffering

### ISSUE THREAD

**Issue by jpwsutton** [jpwsutton/paho.mqtt.java#1]
This is my private checklist for implementing eclipse/paho.mqtt.java#9

To-Do:
- [x] Implement Automatic Reconnect
  - [x] MqttConnectOptions.setAutomaticReconnect
  - [x] MqttCallbackExtended.connectionLost
  - [x] MqttCallbackExtended.connectComplete
  - [x] MqttAsyncClient.reconnect
- [ ] Create Sample App to test & explain how to use Automatic Reconnect
- [x] Unit Tests for Automatic Reconnect
- [x] Implement Offline Buffering
  - [x] DisconnectedBufferOptions
  - [x] DisconnectedMessageBuffer
  - [x] MqttAsyncClient.setBufferOpts
  - [x] MqttAsyncClient.getBufferedMessagesCount
  - [x] MqttAsyncClient.getBufferedMessage
  - [x] MqttAsyncClient.deleteBufferedMessage
  - [x] Persist Buffered Messages to persistence layer
- [ ] Create Sample App to test & explain how to use Offline Buffering
- [x] Unit Tests for Offline Buffering
- [ ] Documentation
